### 참고자료  
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [2]:
import numpy as np

### np.empty() & np.empty_like()
##### Return a new array of given shape and type, ___without initializing entries.___

In [6]:
np.empty((2, 3))    #초기화 시키지 않은 (2, 3)의 배열을 생성한다
one_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
another_array = np.empty_like(one_array)    #one_array와 동일한 dimensions의 초기화되지 않은 배열을 생성한다


[[1489455624        391    4718676]
 [   4390973    6029370    7536725]
 [   7471205    6029427    6357106]]


### np.zeros()  
##### Return a new array of given shape and type, ___filled with zeros.___

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2, 3), dtype=int)    #dtype('int32')

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones()  
##### Return a new array of given shape and type, ___filled with ones.___

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones((2, 3), dtype=float)    #dtype('float64')

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.identity()  
##### Return ___the identity array.___ (정방 단위 행렬 생성)

 - ndarray가 matrix보다 넓은 개념이다
 - ndarray의 dimensions: (2, 2)일 때 matrix라고 부른다

In [4]:
np.identity(2)    #_.dtype('float64')

dtype('float64')

In [5]:
np.identity(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### np.eye()  
##### Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(3)    #np.identity(3) 과 동일
np.eye(3, 4)    #dimensions(3, 4), 대각 행렬이 1인 sparse matrix 생성
np.eye(3, 4, 1)    #위의 행렬에서 대각 행렬이 위로 1칸 올라간 sparse matrix
np.eye(3, 4, -1)    #np.eye(3, 4) 행렬에서 대각 행렬이 아래로 1칸 내려간 행렬

In [1]:
import numpy as np

### np.full()  
##### np.full(shape, fill_value, dtype=None, order='C')  
##### Return a new array of given shape and type, ___filled with fill_value.___

In [2]:
np.full((3, 4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [3]:
#위의 방식보다는 아래 방식을 선호한다.
10 * np.ones((3, 4), dtype='int')

array([[10, 10, 10],
       [10, 10, 10]])

### np.arange()
##### Return ___evenly spaced values___(고르게 위치한 값들) within a given interval.

In [5]:
# default value
# start = 0
# step = 1
np.arange(10)

In [7]:
np.arange(start=1.0, stop=5.0, step=0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### np.linspace()
##### Return evenly spaced numbers over a specified interval.

In [8]:
np.linspace(2.0, 3.0, num=5)    # 2.0과 3.0 사이에 num(=5) 만큼 array를 만든다

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

## __예제__

#### Q1. 2*2 integers 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [11]:
np.empty((2, 2), dtype='int')

array([[-1338743015,  -926147129],
       [  905317606, -1712771826]])

#### Q2. sample_array([[1, 2, 3], [4, 5, 6]], dtype='int32')일 때,  
#### sample_array와 동일한 shape를 가지는 다차원 배열을 초기화 하지 않는 상태로 생성하세요.

In [18]:
sample_array = np.array(([1, 2, 3], [4, 5, 6]), dtype='int32')
q2_array = np.empty_like(sample_array)
q2_array

array([[1, 2, 3],
       [4, 5, 6]])

#### Q3. 크기가 3인 단위행렬을 생성하세요.

In [18]:
q3_array = np.identity(3)

#### Q4. 모든 원소가 1인 3*2 실수형 다차원 배열을 생성하세요.

In [19]:
q4_array = np.ones((3, 2), dtype='float')

#### Q5. sample_array = np.arange(4, dtype=np.int64) 일 때,  
#### sample_array와 동일한 shape를 가지고 모든 원소가 1인 다차원 배열을 생성하세요.

In [33]:
sample_array = np.arange(4, dtype=np.int64)
q5_array = np.ones_like(sample_array)

#### Q6. 모든 원소가 0인 3*2 실수형 다차원 배열을 생성하세요.

In [41]:
q6_array = np.zeros((3, 2), dtype=float)

#### Q7. sample_array = np.arange(4, dtype=np.int64) 일 때,  
#### sample_array와 동일한 shape의 영행렬을 생성하세요.

In [42]:
sample_array = np.arange(4, dtype='int64')
q7_array = np.zeros_like(sample_array)

#### Q8. 모든 원소가 6인 2*5 uint형 다차원 배열을 생성하세요.

In [47]:
q8_array_1 = 6 * np.ones((2, 5), dtype='uint')
q8_array_2 = np.full((2, 5), 6, dtype='uint32')

#### Q9. sample_array = np.arange(4, dtype='int64') 일 때,  
#### sample_array와 동일한 shape이고 모든 원소가 6인 다차원 배열을 생성하세요.

In [55]:
sample_array = np.arange(4, dtype='int64')
q9_array = np.full_like(sample_array, 6)

#### Q10. sam_list = [1, 2] 일 때,  sam_list 를 배열로 변환하세요.

In [60]:
sam_list = [1, 2]
q10_array = np.array(sam_list)
q10_array = np.asarray(sam_list)

In [63]:
q11_array = np.array(sam_list, dtype=float)
q11_array = np.asarray(sam_list, dtype=float)
q11_array = np.asfarray(sam_list)

### > Numerical ranges

#### Q12. 2, 4, 6, 8, ..., 100 을 원소로 가지는 배열을 생성하세요.

In [65]:
q12_array = np.arange(start=2, stop=102, step=2)
q12_array = np.arange(2, 102, 2)

#### Q13. 3.0 에서 10.0 까지 50 개의 원소가 균일하게 분포된 1차원 배열을 생성하세요.

In [20]:
a = np.linspace(3.0, 10.0, 50)
a

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [67]:
q13_array = np.linspace(start=3.0, stop=10.0, num=50)    #np.arange(, stop=10)은 10 미만, np.linspace(, stop=10)은 10 이하
q13_array = np.linspace(3, 10, 50)
q13_array = np.linspace(3.0, 10.0, 50)    #.0을 찍어주는 것이 코딩 표준이다