### 참고자료  
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [3]:
import numpy as np

### np.empty() & np.empty_like()
##### Return a new array of given shape and type, ___without initializing entries.___

In [6]:
np.empty((2, 3))    #초기화 시키지 않은 (2, 3)의 배열을 생성한다
one_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
another_array = np.empty_like(one_array)    #one_array와 동일한 dimensions의 초기화되지 않은 배열을 생성한다


[[1489455624        391    4718676]
 [   4390973    6029370    7536725]
 [   7471205    6029427    6357106]]


### np.zeros()  
##### Return a new array of given shape and type, ___filled with zeros.___

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2, 3), dtype=int)    #dtype('int32')

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones()  
##### Return a new array of given shape and type, ___filled with ones.___

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones((2, 3), dtype=float)    #dtype('float64')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#8' 25'' 부터 시작