In [63]:
import numpy as np
import matplotlib.pyplot as plt
import random

## ___Chapter_01___

In [ ]:
arr_1 = np.array(0)
arr_2 = np.array((0))

In [ ]:
arr_1 = np.array((0, 1))
arr_2 = np.array([0, 1])

In [ ]:
# transpose 를 나타내는 방법: strides
arr_1 = np.array([[1, 2], [3, 4]])    
    # == arr_1 = np.array(((1, 2), (3, 4)))
arr_2 = np.array([[1, 2], [3, 4]], dtype='int64')    # (= dtype=np.int64)
arr_3 = arr_1.T
print(arr_1.strides, '\n', arr_3.strides)

#### c.f) ___TypeError : 'something' object is not callable___ 
#### &nbsp;&nbsp; 호출자로서(= something()) 으로 사용 불가하다는 Error Raise 이다

## ___Chapter_02___

In [43]:
# np.mean()과 np.average() 의 차이점
aver_1 = np.mean(range(1, 11))
aver_2 = np.average(range(1, 11), weights=range(1, 11))
print(aver_1, aver_2)

5.5 7.0


In [62]:
# 데이터 타입에 따른 strides 변화
array_int64 = np.array([[1, 2], [3, 4]], dtype=np.int64)
array_int32 = np.array([[1, 2], [3, 4]], dtype=np.int32)
print('array_int32_strides:', array_int32.strides)
print('array_int64_strides:', array_int64.strides)

array_int32_strides: (8, 4)
array_int64_strides: (16, 8)


## ___Chapter_03___

In [83]:
empty_arr = np.empty((4, 4))    
    # np.empty([4, 4])는 가능
    # np.empty(4, 4)는 불가능: 첫번째 parameter로 shape를 받기 때문에 묶어야 한다
another_empty_arr = np.empty_like(empty_arr)

In [83]:
zero_arr = np.zeros((4, 4))
another_zero_arr = np.zeros_like(zero_arr)

In [83]:
one_arr = np.ones((4, 4))
another_one_arr = np.ones_like(one_arr)

In [83]:
id_arr = np.identity(4)
    # np.identity()는 단위행렬을 만든다
    # 첫 parameter 는 int type을 받는다

In [ ]:
np.eye(3)    # = np.identity(3)
np.eye(3, 5, -1)
    # 3X5 행렬에서 대각 -1 행렬이 1인 행렬

In [ ]:
np.arange(start=1.0, stop=10.5, step=0.5)
    # == np.arange(1, 11, 0.5)

In [ ]:
np.linspace(start=2.0, stop=3.0, num=10)
    # 2.0 과 3.0 사이 범위를 가지는 10개의 행렬을 만든다
    # == np.linspace(2, 3, 10)

## ___Chapter_04___

In [98]:
arr_3d = np.arange(1, 19).reshape(2, 3, 3)
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [97]:
np.amax(arr_3d, 2)

array([[ 3,  6,  9],
       [12, 15, 18]])