In [1]:
import numpy as np

## c.f) Axises(축)  
  #### &nbsp; - axis=0: 행을 따라서 순환한다(세로 순환) = 행의 인덱스를 증가시키며 순환한다 => arr[ : ,  0 ], arr[ : ,  1 ], arr[ : ,  2 ], arr[  : ,  3 ], ... 
  #### &nbsp; - axis=1: 열을 따라서 순환한다(가로 순환) = 열의 인덱스를 증가시키며 순환한다 => arr[ 0 ,  : ], arr[ 1 ,  : ], arr[ 2 ,  : ], arr[ 3 ,  : ], ...

# 통계 관련 메서드

  ### numpy.amin()
  - ##### Return the ___minimum of an array___ or ___minimum along an axis.___

In [21]:
ex_array = np.arange(1, 10).reshape(3, 3)
print(ex_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
np.amin(ex_array, 0) 
    # np.amin(ex_array, axis=0) 
    # => axis=0 이므로  ex_array[:, 0], ex_array[:, 1], ex_array[:, 2] 각각의 최소값을 Return

array([1, 2, 3])

In [29]:
np.amin(ex_array, 1)
    # np.amin(ex_array, axis=1) 
    # => axis=1 이므로 ex_array[0, :], ex_array[1, :], ex_array[2, :] 각각의 최소값을 Return

In [32]:
np.amin(ex_array)    #array 내 모든 요소들 중 최소값

1

### numpy.amax()
 - ##### Return the ___maximum of an array or maximum along an axis.___

### numpy.ptp()
 - ##### Return ___range of values (maximum - minimum) along an axis.___
 - The name of the function comes from the acronym for ___'peak to peak'___

In [37]:
print(np.ptp(ex_array, 0), np.ptp((ex_array), 1))

[6 6 6] [2 2 2]


### numpy.median() (= 중앙값, 중위수)
 - ##### ___Compute the median___ along the specified axis.

In [38]:
np.median(ex_array, 0)

array([4., 5., 6.])

### numpy.mean()

### numpy.var() (= 분산)
 - ##### ___Compute the variance___ along the specified axis.

In [40]:
print(np.var((ex_array), 0), np.var((ex_array), 1), np.var((ex_array)))

[6. 6. 6.] [0.66666667 0.66666667 0.66666667] 6.666666666666667


### numpy.std() (= 표준편차)
 - ##### ___Compute the standard deviation___ along the specified axis.

In [41]:
np.std((ex_array), 1)

array([0.81649658, 0.81649658, 0.81649658])