In [2]:
import numpy as np

## __Shape 변경__

### numpy.reshape()
 - ##### ___Gives a new shape___ to an array without changing its data.

In [10]:
arr = np.arange(6).reshape((3, 2))
print(arr)

[[0 1]
 [2 3]
 [4 5]]


In [8]:
np.reshape(arr, (2, 3))

In [11]:
np.reshape(arr, (1, 6))    #[[0, 1, 2, 3, 4, 5]]
    # 1행 6열의 다차원 배열이 나왔다 (2차원)
    # 귀찮아도 이렇게 적는 것이 차원을 낮추지 않는 방법이다

array([[0, 1, 2, 3, 4, 5]])

In [12]:
np.reshape(arr, 6)    #[0, 1, 2, 3, 4, 5]
    # 6열의 1차원 배열이 나왔다

array([0, 1, 2, 3, 4, 5])

### numpy.ravel()
 - ##### Return a ___contiguous flatted array.___
 - ##### Neuron Network 학습시, 1차원으로 변환하여 넣어준다

In [13]:
np.ravel(arr)    # [0, 1, 2, 3, 4, 5]
    # 1차원의 선형 행렬로 만들어준다

In [14]:
arr.ravel()    # [0, 1, 2, 3, 4, 5]
    # 위와 동일한 결과

 - ##### NumPy 모듈 안의 ravel 함수로 사용할 수도 있고  
 - ##### ndarray type 안에 있는 ravel 메서드로도 사용할 수 있다

### numpy.ndarray.flatten()
 - ##### Return a copy of the array collapsed into one dimension.

In [19]:
# np.flatten(arr)    # NumPy 모듈 함수가 아니다
arr.flatten()    # ndarray 객체의 메소드로만 사용 가능

array([0, 1, 2, 3, 4, 5])

### ravel() 과 flatten() 의 차이점
 - #### ravel() 은 뷰를 반환(reference, 값을 참조해서 반환)  
 - #### flatten() 은 복사본을 반환(value duplicate, 값을 복사해서 반환)
 - #### flatten() 은 객체의 메서드로만 사용가능

## __연결__

### numpy.concatenate()

In [21]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6]])

In [22]:
np.concatenate((arr_1, arr_2), axis=0)    # axis=0이면 row를 따라 순회하므로 새로운 row를 만든다
    # array([[1, 2],
    #        [3, 4],
    #        [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.concatenate((arr_1, arr_2.T), axis=1)     # shape를 맞추기 위해서 arr_2를 Transpose 했다 
    # 1차원은 Transpose가 안되지만 arr_2.shape은 (2, 1)로 2차원이
    # array([[1, 2, 5],
    #        [3, 4, 6]])

In [35]:
# 인덱싱 후 Transpose
arr_1[0].T    # 1차원에서 Transpose 하면 변화가 없다
arr_1[0:1].T    # 이렇게 slicing을 해야한다

array([[1],
       [2]])

#### 참조 (https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html#joining-arrays)

#### Q1. x가 10X10X3 의 다차원 배열일 때, x의 두번째 차원이 150인 2차원 배열이 되도록 reshape 하세요.

In [46]:
x = np.zeros((10, 10, 3), dtype='int') # 10pages, 10rows, 3cols
x.reshape((2, 150))

#### Q2. x가 [[1, 2, 3], [4, 5, 6]] 일 때, [1 4 2 5 3 6] 으로 변환하세요

In [51]:
x = np.array([[1, 2, 3], [4, 5, 6]])
    # x.T.ravel() == np.ravel(x.T) == x.T.flatten()

#### Q3. x가 [[1, 2, 3], [4, 5, 6]] 일 때, flatten한 후, 다섯 번째 원소를 가져오세요.

In [56]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.flatten()[5]

6

#### Q4. x = [[1, 2, 3], [4, 5, 6]] , y = [[7, 8, 9], [10, 11, 12]] 일 때,
#### x와 y를 연결하여 [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]를 만드세요.

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate((x, y), axis=1)

#### Q5. x가 [0, 1, 2]일 때, [0, 0, 1, 1, 2, 2]를 생성하세요

In [71]:
x = np.array([0, 1, 2])
np.repeat(x, 2)

array([0, 0, 1, 1, 2, 2])

#### Q6. x가 [0, 0, 0, 1, 2, 3, 0, 2, 1, 0] 일 때, 앞, 뒤의 0을 제거하세요.

In [76]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
x[3:-1]
    # np.trim_zeros(x)    #Deep Learning에서 사용한다

array([1, 2, 3, 0, 2, 1])

## __다차원 배열 연산__

### 기본적인 수학함수는 배열의 각 요소별로 동작하며 연산자를 통해 동작하거나 NumPy 함수 모듈을 통해 작동합니다.  
### 다차원 배열간 연산시, shape가 맞아야 연산이 이루어집니다.
 - #### 요소별 합, 차, 곱, 나누기의 경우 shape가 일치해야 합니다.
 - #### dor의 경우, 앞 배열의 열과 뒤 배열의 행의 크기가 일치하여야 합니다.
참고(https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [82]:
x = np.array([[1., 2.], [3., 4.]])
y = np.array([[5., 6.], [7., 8.]])

# 요소별 합: 둘 다 다음의 배열을 만듭니다.
# [[ 6.0  8,0]
#  [10.0 12.0]])
print(x + y)
print(np.add(x, y))

# 요소 별 차: 둘 다 다음의 배열을 만듭니다.
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# 요소 별 곱: 둘 다 다음의 배열을 만듭니다.
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# 요소 별 나누기: 둘 다 다음의 배열을 만듭니다.
# y의 요소 중 0이 있으면 오류가 발생한다.
# [[0.2        0.33333333]
#  [0.42857143 0.5       ]]
print(x / y)    
print(np.divide(x, y))

# 요소 별 제곱근: 다음의 배열을 만듭니다.
# [[1.         1.41421356]
#  [1.73205081 2.        ]]
print(np.sqrt(x))

#### NumPy 에선 벡터의 내적, 벡터와 행렬의 곱, 행렬곱을 위해 * 대신 dot 함수를 사용합니다.
#### dot 은 NumPy 모듈 함수로서도 배열 객체의 메소드로서도 이용이 가능한 함수입니다.

In [93]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])    # 1차원 다차원 배열 == 벡터
w = np.array([11, 12])    # 1차원 다차원 배열 == 벡터

# 벡터의 내적: 둘 다 결과는 219
print(v.dot(w))
print(np.dot(v, w))

# 행렬과 벡터의 곱: 둘 다 결과는 dimension 1인 배열 [29 67]
print(x.dot(v))
print(np.dot(x, v))

# 행렬 곱: 둘 다 결과는 dimension 2인 배열
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
