# ___Introduction of NumPy___

In [7]:
import numpy as np

math_score = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
math_score_ndarray = np.array(math_score)

# 각 원소에 1을 더하려면 
print('Math Score: \n', math_score_ndarray)
added_math_score_ndarray = math_score_ndarray + 1    # broadcastiong
print('Math Score + 1: \n', added_math_score_ndarray)

print(np.average(math_score_ndarray, axis=0))    # 열(col) 별 평균 구하기
print(np.average(math_score_ndarray, axis=1))   # 행(row) 별 평균 구하기

Math Score: 
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Math Score + 1: 
 [[12 13 14]
 [22 23 24]
 [32 33 34]]
[21. 22. 23.]
[12. 22. 32.]


In [ ]:
#속도 비교 (크기 100개 이내인 경우, NumPy는 기본 파이썬 구현보다 낮은 성능(늦은 시간)을 보이는 경향이 있다)

import time

class Timer(object):
    def __init__(self, name=None):
        self.name = name
    def __enter__(self):
        self.tstart = time.time()
    def __exit__(self, type, value, traceback):
        if self.name:
            print("[%s]"%self.name)
        print('Elapsed: %.10f'%(time.time() - self.tstart))

#Timer 사용법
with Timer('여기에 이름을 입력하세요'):
    #아래에 시간 측정을 하고자 하는 코드를 입력하세요.
    time.sleep(1)

In [42]:
rows = 5
cols = 5

rand_2darray = np.random.rand(rows, cols)    #ndarray 선언
rand_2dlist = rand_2darray.tolist()    #nested list 선언

In [43]:
with Timer('파이썬 기본 자료형 사용 - 모든 원소의 합 구하기'):
    sum  = 0
    
    for list in rand_2dlist:
        for i in list:
            sum += i
            
with Timer('파이썬 기본 자료형 사용 - 모든 원소에 1 더하기'):
    rand_2dlist_2 = []
    
    for list in rand_2dlist:
        temp_list = []
        
        for i in list:
            temp_list.append(i + 1)
            
    rand_2dlist_2.append(temp_list)
            
print("--------------------------------------------")

with Timer('NumPy 사용 - 모든 원소의 합 구하기'):
    sum = np.sum(rand_2darray)
    
with Timer('NumPy 사용 - 모든 원소에 1 더하기'):
    rand_2darray_2 = rand_2darray + 1
    

[파이썬 기본 자료형 사용 - 모든 원소의 합 구하기]
Elapsed: 0.000000000000000000000000000000
[파이썬 기본 자료형 사용 - 모든 원소에 1 더하기]
Elapsed: 0.000000000000000000000000000000
--------------------------------------------
[NumPy 사용 - 모든 원소의 합 구하기]
Elapsed: 0.000000000000000000000000000000
[NumPy 사용 - 모든 원소에 1 더하기]
Elapsed: 0.000000000000000000000000000000


## Numpy장점
 - ### 코어 부분이 C로 구현되어 동일한 연산을 하더라도 Python에 비해 속도가 빠름
 - ### 라이브러리에 구현되어있는 함수들을 활용해 짧고 간결한 코드 작성 가능
 - ### (효율적인 메모리 사용이 가능하도록 구현됨)

## Python list가 느린 이유
 - ### list는 결국 포인터의 배열
 - ### 경우에 따라서 각각 객체가 메모리 여기저기에 흩어져 있음
 - ### 그러므로 캐시 활용이 어려움

## NumPy ndarray가 빠른 이유
 - ### ndarray는 타입을 명시(동일한 bytes를 이동하며 연산)하여 원소의 배열로 데이터를 유지
 - ### 다차원 데이터도 연속된 메모리 공간이 할당됨
 - ### 많은 연산이 dimensions과 strides를 잘 활용하면 효율적으로 가능 (가령 transpose는 strides를 바꾸는 것이 거의 공짜)
 - ### ndarray 구현 방식을 떠올리면 어떻게 성능을 낼 수 있는지 상상 가능

In [58]:
#NumPy에서 Transpose(전치행렬) 구현
x_array = np.array([[1, 2], [3, 4]], dtype=np.int8)
y_array = x_array.T
print(x_array, '\n\n', y_array)
print('\n', "x_array's strides: ", x_array.strides, '\n', "y_array's strides: ", y_array.strides)

[[1 2]
 [3 4]] 

 [[1 3]
 [2 4]]

 x_array's strides:  (2, 1) 
 y_array's strides:  (1, 2)


### x_array => Data: 1 2 3 4 / Dimension: (2, 2) / Strides: (2, 1) 

### y_array => Data: 1 2 3 4 / Dimension: (2, 2) / Strides: (1, 2) 

### strides: (r, c)라고 한다면 첫번째 요소[0][0]에서 +r 데이터가 [1][0]이고 +c 데이터가 [0][1]이라는 뜻이다
  - #### => NumPy에서 Transpose 하는 과정이 매우 간단