## __Numpy 고급 기능__

#### ___Broadcasting___은 NumPy 에서 shape 가 다른 배열 간에도 산술 연산이 가능하게 하는 메커니즘이다. 종종 작은 배열과 큰 배열이 있을 때,
#### 큰 배열을 대상으로 작은 배열을 여러 번 연산하고자 할 때가 있습니다. 예를 들어, 행렬의 각 행에 상수 벡터를 더하는 걸 생각해보세요.
#### 이는 다음과 같은 방식으로 처리될 수 있습니다.

In [5]:
import numpy as np

# 행렬 x와 각 행에 벡터 v를 더한 뒤
# 그 결과를 행렬 y에 저장하고자 합니다.
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
    # [[ 1  2  3]
    #  [ 4  5  6]
    #  [ 7  8  9]
    #  [10 11 12]]
    
v = np.array([1, 0, 1])    # 1차원 배열(벡터)
y = np.empty_like(x)

# 명시적 반복문을 통해 행렬 x와 각 행에 벡터 y를 더하는 방법
for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)    

    # [[ 2  2  4]
    #  [ 5  5  7]
    #  [ 8  8 10]
    #  [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### 위의 방식대로 하시면 됩니다. 그러나 x가 매우 큰 행렬이라면, 파이썬의 반복문을 이용한 위 코드는 매우 느려질 수 있습니다.
#### 벡터 v를 행렬 x의 각 행에 더하는 것은 v를 여러 개 복사해 수직으로 쌓은 행렬 vv를 만든고 이 vv를 x와 더하는 것과 동일합니다.
#### 위 과정을 아래처럼 구현할 수 있습니다.

In [ ]:
# 벡터 v를 행렬 x의 각 행에 더한 뒤, 그 결과를 행렬 y에 저장하고자 합니다
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))    # v의 복사본 4개를 위로 차곡차곡 쌓은 것이 vv vv.shape == (4, 3)
    # [[1 0 1]
    #  [1 0 1]
    #  [1 0 1]
    #  [1 0 1]]
y = x + vv
print(y)

    # [[ 2  2  4]
    #  [ 5  5  7]
    #  [ 8  8 10]
    #  [11 11 13]]

#### ___Numpy Broadcasting___ 을 이용한다면 이렇게 v의 복사본을 여러 개 만들지 않아도 동일한 연산을 할 수 있습니다. 
#### 아래는 ___Broadcasting___ 을 이용한 예시 코드입니다.

In [9]:
# 벡터 v를 행렬 x의 각 행을 더한 뒤, 그 결과를 행렬 y에 저장하고자 합니다.
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v    # broadcasting 을 이용하여 v와 x를 각 행에 더하기
print(y)

    # [[ 2  2  4]
    #  [ 5  5  7]
    #  [ 8  8 10]
    #  [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### x 의 shape가 (4, 3) 이고 v 의 shape 가 (3, )이라도 브로드캐스팅으로 인해 y = x + v 는 문제없이 수행됩니다.
#### 이때, v는 v의 복사본이 차곡차곡 쌓인 shape (4, 3) 처럼 간주되어 x 와 동일한 shape 가 되며 이들 간의 요소별 덧셈연산이 y에 저장됩니다.
#### 두 배열의 Broadcasting 은 아래의 규칙을 따릅니다 :
 - ##### 두 배열이 동일한 dimension을 가지고 있지 않다면, 낮은 dimension 의 1차원 배열이 높은 dimension 배열의 shape로 간주됩니다.
 - ##### 특정 차원에서 두 배열이 동일한 크기를 갖거나, 두 배열 중 하나의 크기가 1이라면 그 두 배열은 특정 차원에서 compatible 하다고 여겨집니다.
 - ##### 두 행렬이 모든 차원에서 compatible 하다면, 브로드캐스팅이 가능합니다.
 - ##### 브로드캐스팅이 이루어지면, 각 배열 shape 의 요소별 최소공배수로 이루어진 shape가 두 배열의 shape로 간주됩니다.
 - ##### 차원에 상관없이 크기가 1인 배열과 1보다 큰 배열이 있을 때, 크기가 1인 배열은 자신의 차원 수만큼 복사되어 쌓인 것처럼 간주됩니다.

#### 브로드캐스팅을 지원하는 함수를 universal function 이라고 합니다
#### (참고 : https://docs.scipy.org/doc/numpy/reference/ufuncs.html)
#### 아래는 브로드캐스팅을 응용한 예시들입니다.

### ___c.f)___
#### Chapter_1 에서 했던 math_score_ndarray + 1은 ___'ndarray + scalar'___ 의 계산으로 dimension이 맞지 않으나 Broadcasting을 사용
#### math_score_ndarray ___+ 1___ == math_score_ndarray ___+ np.ones_like(math_score_ndarray)___ 였던 것이다

In [11]:
v = np.array([1, 2, 3])    # v.shape == (3,)
w = np.array([4, 5])    # w.shape == (2, )
x = np.array([[1, 2, 3], [4, 5, 6]])    # x.shape == (2, 3)

In [11]:
# 벡터를 행렬의 각 행에 더하기 
# x는 shape가 (2, 3)이고 v는 shape가 (3, )이므로 이 둘을 브로드캐스팅하면 shape가 (2, 3)
print(x + v)
    # [[2 4 6]
    #  [5 7 9]]

In [15]:
# 벡터를 각 행렬의 각 행에 더하기
# x.shape = (2, 3), w.shape = (2, )
# x.T.shape = (3, 2) 이며, 이는 w와 브로드캐스팅이 가능하고 그 결과 shape는 (3, 2)
#위 연산 결과 행렬을 전치하면 (2, 3)인 행렬이 나오며 이는 행렬 x의 각 열에 벡터 w를 더한 결과와 동일하다.
print((x.T + w).T)
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [16]:
# 행렬의 스칼라배 
# x.shape = (2, 3)입니다. NumPy는 스칼라를 shape가 ()인 배열로 취급합니다.
# 그렇기에 스칼라 값은 (2, 3) shape로 브로드캐스팅할 수 있습니다.
print(x + 2)

[[3 4 5]
 [6 7 8]]
